In [2]:
import pandas as pd
pd.__version__


'1.4.4'

In [3]:
wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

SyntaxError: invalid syntax (3069519253.py, line 1)

In [41]:
df=pd.read_csv("car_fuel_efficiency.csv")

In [10]:
df.head(30)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                   170            3.0       159.0     3413.433759   
1                   130            5.0        97.0     3149.664934   
2                   170            NaN        78.0     3079.038997   
3                   220            4.0         NaN     2542.392402   
4                   210            1.0       140.0     3460.870990   
5                   190            3.0         NaN     2484.883986   
6                   240            7.0       127.0     3006.542287   
7                   150            4.0       239.0     3638.657780   
8                   250            1.0       174.0     2714.219310   
9                   150            4.0       123.0     3509.036569   
10                  230            5.0       100.0     3111.810181   
11                  150            5.0         NaN     1967.200421   
12                  320            5.0       145.0     2783.868974   
13                  170            1.0       193.0     2274.735191   
14                  200            6.0       160.0     3582.687368   
15                  220            4.0       179.0     2631.065204   
16                  160            3.0       180.0     2673.552941   
17                  190            6.0       132.0     2427.311856   
18                  250            2.0       110.0     2971.214575   
19                  180            1.0       126.0     2986.958657   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   
22                  190            1.0       144.0     2438.842126   
23                  230            2.0       160.0     3342.606027   
24                  260            3.0       156.0     4267.390497   
25                  210            6.0       157.0     2860.206191   
26                  180            8.0       160.0     3080.170162   
27                  120            6.0       206.0     3467.355490   
28                  220            4.0       154.0     3335.068187   
29                  230            4.0       132.0     2479.782974   

    acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0           17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1           17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2           15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3           20.2        2009     USA    Diesel    All-wheel drive        2.0   
4           14.4        2009  Europe  Gasoline    All-wheel drive        2.0   
5           14.7        2008  Europe  Gasoline    All-wheel drive       -1.0   
6           22.2        2012     USA  Gasoline  Front-wheel drive        1.0   
7           17.3        2020     USA    Diesel    All-wheel drive        1.0   
8           10.3        2016    Asia    Diesel  Front-wheel drive       -1.0   
9           10.2        2005     USA  Gasoline  Front-wheel drive       -1.0   
10          15.4        2014  Europe    Diesel    All-wheel drive        0.0   
11          12.6        2014     USA    Diesel  Front-wheel drive        2.0   
12          15.1        2010    Asia    Diesel    All-wheel drive        1.0   
13          17.5        2000  Europe    Diesel  Front-wheel drive        0.0   
14          14.9        2007    Asia    Diesel    All-wheel drive        0.0   
15          16.0        2006     USA  Gasoline    All-wheel drive        1.0   
16           8.5        2013  Europe    Diesel    All-wheel drive       -1.0   
17          17.8        2011     USA    Diesel  Front-wheel drive       -1.0   
18           NaN        2003  Europe  Gasoline  Front-wheel drive        1.0   
19          17.9        2004  Europe  Gasoline    All-wheel drive       -1.0   
20          18.7        2011    Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016    Asia  Gasoline  Front-wheel drive       -

In [6]:
df.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [11]:
df['fuel_type'].value_counts()

Gasoline    4898
Diesel      4806
Name: fuel_type, dtype: int64

In [13]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [23]:
# Filter for Asian cars only
asian_cars = df[df['origin'] == 'Asia']

# Find the maximum fuel efficiency for Asian cars
max_fuel_efficiency_asia = asian_cars['fuel_efficiency_mpg'].max()

In [24]:
print (max_fuel_efficiency_asia )

23.759122836520497


In [26]:
df['horsepower'].median()

149.0

In [35]:
df['horsepower'].mode()[0]

152.0

In [43]:
df['horsepower'].fillna(df['horsepower'].mode()[0], inplace=True)

In [44]:
df['horsepower'].median()

152.0

In [48]:
# Filter for Asian cars only
asian_cars_update = df[df['origin'] == 'Asia']
asian_cars_update

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [56]:
select_asians=asian_cars_update[["vehicle_weight","model_year"]]
select_asians.head(7)
x=select_asians.head(7).values
print (x)

[[2714.21930965 2016.        ]
 [2783.86897424 2010.        ]
 [3582.68736772 2007.        ]
 [2231.8081416  2011.        ]
 [2659.43145076 2016.        ]
 [2844.22753389 2014.        ]
 [3761.99403819 2019.        ]]


In [60]:
import numpy as np
xtx = np.dot(x.T, x)
print(xtx)

[[62248334.33150762 41431216.50732678]
 [41431216.50732678 28373339.        ]]


In [61]:
xtx_inverse = np.linalg.inv(xtx)
print(xtx_inverse)

[[ 5.71497081e-07 -8.34509443e-07]
 [-8.34509443e-07  1.25380877e-06]]


In [63]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print(y)

[1100 1300  800  900 1000 1100 1200]


In [69]:
w = np.dot(np.dot(xtx_inverse,x.T),y)

In [70]:
print(w)

[0.01386421 0.5049067 ]


In [71]:
print(sum(w))

0.5187709081074002
